// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "TrainMenu",
    platforms: [.macOS(.v13)],
    targets: [
        .executableTarget(
            name: "TrainMenu",
            path: "Sources/TrainMenu",
            // The offline snapshot (raw-DEFLATE'd JSON) is generated by
            // Scripts/build-data-snapshot.py before building. See README.
            resources: [.copy("Resources/Data")]
        )
    ]
)
